### PR TITLE
Disable TestFlight during simulations

### PR DESCRIPTION
**Pull request by ts826848**
This isn't done yet; I got something working, but I'm not sure how to make it work when TF isn't actually around. What is the proper way of doing such a thing?

It's also super hacky, since it meddles with TestFlightCore directly, but at least it seems to work?

Took a guess as to where the TestFlightCore dll would be on your system. No idea if it's right.

No idea whether the null checks are actually necessary, either.

My apologies for the rather poor PR quality...

### CODE REVIEW

**Comment by ts826848** [comment]
Force pushed with another implementation that uses reflection to only disable TestFlight if it is present. Hopefully this is better?

**Comment by ts826848** [comment]
I think this is ready to be merged, unless a setting to enable/disable TestFlight is desirable.

I considered adding that setting, but me and a few others on #RO think that there really isn't a use case for having TestFlight enabled during a sim, since there's currently no way to manually force a failure to occur.

**Comment by 7ranceaddic7** [comment]
Does the module TestFlightReliability_TestFail not really trigger failures for debugging?

**Comment by ts826848** [comment]
@7ranceaddic7 Ah, yes, you're right. Looks like I didn't look at the TF API closely enough. I'll get that setting added.

**Comment by ts826848** [comment]
Alright, added a toggle to the editor GUI that allows players to enable/disable TF for that sim. Hopefully that's everything?

**Comment by linuxgurugamer** [comment]
Thanks, sorry it took so long to merge

**Pull request merged**
